### ISSUE TITLE
Make this component works with Nuxt

### ISSUE THREAD

**Issue by ansidev** [mengdu/m-dialog#6]
Currently, `m-message` is working with Nuxt, but `m-dialog` isn't. Could you please make it work with Nuxt?
Thank you very much.

**Comment by mengdu** [comment]
You can try create a **plugins/dialog.js**
```js
import Vue from 'vue'
import MDialog from 'vue-m-dialog'

Vue.use(MDialog)
```

Then use on **nuxt.config.js**
```js
plugins: [
    { src: '~/plugins/dialog', ssr: false }
  ]
```

**Comment by ansidev** [comment]
@mengdu 
I tried to use sample code from the documentation, but it didn't work.
By the way, this is the working version for Nuxt plugin file:

```js
import Vue from 'vue'
import MDialog from 'vue-m-dialog/dist'
import 'vue-m-dialog/dist/css/default.css'

Vue.use(MDialog)
```

So I think the documentation is outdated and it should be updated.

**Comment by mengdu** [comment]
OK, I got it. I'll update it later.
